###################
# history options #
###################

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTFILE="$HOME/.zsh/history"
HISTSIZE=10000
SAVEHIST=10000
# Ignore these commands
HISTORY_IGNORE='(ls|bg|fg|history|ll|exit|pwd|cd|cd -|date|* --help|g s|g add -A|e .*|e|g c .*|kill .*|g d|g b|g b -r)'
# Share history between sessions
setopt SHARE_HISTORY
# Write history incrementally (after each command)
setopt INC_APPEND_HISTORY
# Don't record dupes in history
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
# Remove excess blanks in command line
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_SPACE
# Append to history (instead of overwriting it)
setopt APPEND_HISTORY
# Store datetime in history file
setopt EXTENDED_HISTORY
# Allows comments in interactive mode
setopt INTERACTIVE_COMMENTS

#########################
# included config files #
#########################

source ~/.zsh/prompt
source ~/.zsh/alias
source ~/.zsh/func
source ~/.zsh/zshmarks
source ~/.zsh/completion
source ~/.zsh/terminalapp

# Virtual wrapper
if [ -f /usr/share/virtualenvwrapper/virtualenvwrapper.sh ]; then
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
fi

# Hint for missing packages
if [ -f /etc/zsh_command_not_found ]; then
    source /etc/zsh_command_not_found
fi

# Colorization of command line similar to fish shell
# source ~/src/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


####################
# terminal options #
####################

# Rebind codes to what I expect them to do

# delete
bindkey '^[[3~' delete-char
# Ctrl+<arrow>
bindkey ';5C' forward-word
bindkey ';5D' backward-word
# Alt+<arrow>
bindkey ';3D' beginning-of-line
bindkey ';3C' end-of-line
# Ctrl+delete
bindkey '^[[3;5~' kill-word
# Ctrl+backspace
bindkey '^H' backward-kill-word
# Ctrl+r
bindkey '^R' history-incremental-pattern-search-backward
# Alt+backspace
bindkey '\e\C-?' backward-kill-line
# Alt+delete
bindkey '^[[3;3~' kill-line
# Ctrl+z
bindkey '^z' undo

# Disable special handling of ^s and ^q by OS X Terminal
stty -ixon -ixoff
# Bind interrupt to ctrl+shift+c
stty intr '^C'
stty susp '^Z'


###############
# zsh options #
###############

# `**/qux` will enter `./foo/bar/baz/qux`
setopt autocd
# Case-insensitive globbing (used in pathname expansion)
unsetopt CASE_GLOB
# Complete on tab, leave expansion to _expand
bindkey '^I' complete-word
# Stop at directory separator when deleting words
autoload -U select-word-style
select-word-style bash
# Leave background programs running
setopt NO_HUP
# Don't beep when autocompleting
setopt NO_LIST_BEEP
# Use zmv, mass renaming module
autoload -U zmv
alias zmv="noglob zmv -W"


#################
# other options #
#################

# Colored file types for ls
eval $(dircolors -b "$HOME/.dircolors")

# turn off ZLE bracketed paste in dumb term
# otherwise turn on ZLE bracketed-paste-magic
if [[ $TERM == dumb ]]; then
    unset zle_bracketed_paste
else
    autoload -Uz bracketed-paste-magic
    zle -N bracketed-paste bracketed-paste-magic
fi
