- name: Install apt packages
  become: true
  apt: "name={{ item }}"
  with_items:
    # Fonts for text editor and vim
    - fonts-powerline
    - fonts-inconsolata
    # Shell
    - zsh
    # Brother scanning requires this
    - libusb-dev
    # Needed by this notebook
    - python-pip
    # Common dev stuff
    - autoconf
    - automake
    # Version control
    - mercurial
    - git
    # More up to date and avoids poluting the system packages dir
    - python
    # Golang
    - golang
    # Http client
    - wget
    - httpie
    # For watching network traffic
    - ngrep
    # Mass rename
    - rename
    # OpenVPN in network manager
    - network-manager-openvpn-gnome
    # More apps
    - dropbox
    - skypeforlinux
    - vagrant
    # Required by shell prompt
    # - vcprompt
    # File synching
    # - syncthing
    # - spotify
    # - mattermost
    # SSH tunnels
    - gstm

- name: Increase the number of file watches
  become: true
  lineinfile: dest=/etc/sysctl.conf line=fs.inotify.max_user_watches=1048576


