
- name: install homebrew
  command: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)" creates=/usr/local/bin/brew

- name: add homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - osso/formula
    - caskroom/cask
    - caskroom/fonts
    - homebrew/completions

- name: install apps from homebrew
  homebrew: name={{ item }} state=present
  with_items:
    # Gnu utils like ls
    - coreutils
    # Version control
    - git
    - mercurial
    # More up to date and avoids poluting the system packages dir
    - python
    # Golang
    - go
    # File synching
    - syncthing
    # Http client
    - wget
    - httpie
    # For watching network traffic
    - ngrep
    # For installing the mac os x apps
    - brew-cask
    - rename
    # Shell completions
    - vagrant-completion
    - django-completion
    - pip-completion
    - zsh-completions
    - bash-completion
    # Required by zsh
    - gdbm
    # Required by shell prompt
    - vcprompt
    # For drone
    - bazaar
    - ngrok
    # Stuff
    - ssh-copy-id
    - tree
    # Tapir
    - fcgi
    - gettext
    - glib
    - protobuf
    - hiredis
    - log4c
    - avro-c
    - bsdmake
    - pkg-config
    # CoreOS on NAS
    - fleetctl
    - docker

- name: install cask apps from homebrew
  homebrew_cask: name={{ item }} state=present
  with_items:
    - alfred
    - dropbox
    - java
    - skype
    - vagrant
    - virtualbox
    - cleanmymac
    - colloquy
    - grandperspective
    - mplayerx
    - istat-menus
    - font-inconsolata-dz-for-powerline
    - slate
    - timemachineeditor
    - adium
    - transmit
    - onepassword
    # - github
    - bonjour-browser
    - firefox
    - istumbler
    - kismac
    - seashore
    - sourcetree
    - transmission
    - viscosity

- name: Allow homebrew zsh to be selected as default shell
  sudo: true
  lineinfile: dest=/etc/shells line={{ shell_path }}

