###########
# history #
###########

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace:erasedups
# History file location
HISTFILE="$HOME/.bash/history"
# Max commands in history
HISTSIZE=50000
HISTFILESIZE=50000
# Write times in history
HISTTIMEFORMAT="%F %T "
# Do not write these commands in history
HISTIGNORE='ls:bg:fg:history:ll:exit:pwd:cd:cd -:exit:date:* --help'
# Write history to disk after each command
# Emit OSC 7 for terminal to track cwd (new tabs open in same dir)
_osc7_pwd() { printf '\e]7;file://%s%s\e\\' "${HOSTNAME:-$(hostname)}" "$PWD"; }
PROMPT_COMMAND="_osc7_pwd; history -a; $PROMPT_COMMAND"
# append to the history file, don't overwrite it
shopt -s histappend
# Load history from file on startup (needed for brush shell)
history -r


############
# includes #
############

source ~/.bash/env
source ~/.bash/prompt
source ~/.bash/alias
source ~/.bash/func

################
# autocomplete #
################

# Homebrew autocompletion
if [ -f /usr/local/etc/bash_completion ]; then
    source /usr/local/etc/bash_completion
fi

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2 | tr ' ' '\n')" scp sftp ssh;
# Complete killall with running process names
_killall_complete() {
    COMPREPLY=($(compgen -W "$(ps -eo comm= | sort -u)" -- "${COMP_WORDS[COMP_CWORD]}"))
}
complete -F _killall_complete killall
# Git completion
source /usr/share/git/completion/git-completion.bash
__git_complete g __git_main


################
# bash options #
################

# Autocorrect typos in path names when using `cd`
shopt -s cdspell
# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob
# ** recursive glob
shopt -s globstar
# Update LINES/COLUMNS after window resize
shopt -s checkwinsize
# Autocorrect dir names in completion
shopt -s dirspell
# Multi-line commands as single history entry
shopt -s cmdhist

# Rebind codes to what I expect them to do

# # Ctrl+<arrow>
# bind '"\e[1;5C": forward-word'
# bind '"\e[1;5D": backward-word'
# # Alt+<arrow>
# bind '"\e[1;3D": beginning-of-line'
# bind '"\e[1;3C": end-of-line'
# # Ctrl+delete
# bind '"\e[3;5~":kill-word'
# # Ctrl+backspace
# bind '\C-H: backward-kill-word'
# # Alt+backspace
# bind '"\e\C-?": backward-kill-line'
# # Alt+delete
# bind '"\e[3;3~": kill-line'
